### ISSUE TITLE
Multi-domain image trranslation

### ISSUE THREAD

**Issue by leoliu37** [Alexander-H-Liu/UFDN#2]
Thanks for your demo. I am interested in the multi-domain image translation.Could you provide the related attribute (Gender and Smiling) list ?

**Comment by Alexander-H-Liu** [comment]
Hi,

Sorry, according to [the policy of CelebA](http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html), we've removed the dataset to keep it private

**Comment by leoliu37** [comment]
> Hi,
> 
> Sorry, according to [the policy of CelebA](http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html), we've removed the dataset to keep it private

I have download the CelebA database. Could you only provide the training list and testing list? I could find the attribute label if you provide list files. I want to compare with your method. Thanks a lot!
