### ISSUE TITLE
Multi-domain image translation

### ISSUE THREAD

**Issue by leoliu37** [Alexander-H-Liu/UFDN#3]
Your work is interseting. I am interested in the multi-domian image translation. Could you provide the attribute lable list in experiments. Thanks a lot!

**Comment by leoliu37** [comment]
I have download the CelebA database. Could you only provide the training list and testing list? I could find the attribute label if you provide list files. I want to compare with your method.

**Comment by Alexander-H-Liu** [comment]
@leoliu37 We're currently planning to run our model on a better resolution for the poster, we'll provide information once we've finished.
However, if you're in a rush, I believe split the dataset randomly and run re-train our model produces a similar result reported in the paper.

**Comment by leoliu37** [comment]
> @leoliu37 We're currently planning to run our model on a better resolution for the poster, we'll provide information once we've finished.
> However, if you're in a rush, I believe split the dataset randomly and run re-train our model produces a similar result reported in the paper.

Thanks, I have obtained the CelebA database, but I wander if you can provide the corresponding relationship between each image of your dataset matrix in"face.h5" and the attribute filename in CelebA.
